--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Serenity-sun/WorldWorker
build-by-default: true
branches:
- master
projects:
  WorldWorker:
    main: SerenitySun\WorldWorker\PluginLoader
    path: ""
    icon: icon.png
    lint:
      phpstan: true
      syntaxError: false
...
