name: World-Worker
main: SerenitySun\WorldWorker\PluginLoader
src-namespace-prefix: SerenitySun\WorldWorker
version: 2
api: 5.0.0
author: Serenity-Sun
permissions:
  world-worker.worker:
    default: op
    description: open world-worker form